### ISSUE TITLE
ExceptionInInitializerError in Clojure 1.9

### ISSUE THREAD

**Issue by liquidz** [clojure-emacs/orchard#91]
## Expected behavior

REPL starts with Orchard 0.5.9 and Clojure 1.9.0 normally.

## Actual behavior

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.RuntimeException: Unable to find static field: REQUIRE_LOCK in class clojure.lang.RT, compiling:(clojure/core.clj:6079:3)
        at clojure.lang.Compiler.analyze(Compiler.java:6792)
        at clojure.lang.Compiler.access$300(Compiler.java:38)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6368)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
        at clojure.lang.Compiler.analyze(Compiler.java:6773)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6991)
        at clojure.lang.Compiler.analyze(Compiler.java:6773)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6991)
        at clojure.lang.Compiler.analyze(Compiler.java:6773)
        at clojure.lang.Compiler.analyze(Compiler.java:6729)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5460)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4022)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7001)
        at clojure.lang.Compiler.analyze(Compiler.java:6773)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6991)
        at clojure.lang.Compiler.analyze(Compiler.java:6773)
        at clojure.lang.Compiler.access$300(Compiler.java:38)
        at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:595)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
        at clojure.lang.Compiler.analyze(Compiler.java:6773)
        at clojure.lang.Compiler.analyze(Compiler.java:6729)
        at clojure.lang.Compiler.eval(Compiler.java:7066)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        at clojure.lang.RT.loadResourceScript(RT.java:379)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.load(RT.java:460)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.lang.RT.doInit(RT.java:468)
        at clojure.lang.RT.<clinit>(RT.java:336)
        ... 1 more
Caused by: java.lang.RuntimeException: Unable to find static field: REQUIRE_LOCK in class clojure.lang.RT
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7196)
        at clojure.lang.Compiler.analyze(Compiler.java:6752)
        ... 30 more
Subprocess failed (exit code: 1)
```

## Steps to reproduce the problem

* `lein new foo`
* `cd foo`
* Edit project.clj like below
```
(defproject foo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [cider/orchard "0.5.9"]]
  :repl-options {:init-ns foo.core})
```
* lein repl

### Clojure version

1.9.0

### Java version

1.8

### Operating system

macOS Catalina

**Comment by liquidz** [comment]
I've found the behavior difference like following.

```sh
git clone https://github.com/clojure-emacs/orchard
cd orchard

rm -rf ~/.m2/repository/cider/orchard/0.5.9 && lein with-profile +1.10 install
## => No problem

rm -rf ~/.m2/repository/cider/orchard/0.5.9 && lein install
## => ERROR
```

So it may be mistaken in createing deployed JAR file.

**Comment by bbatsov** [comment]
Hmm, that's pretty weird. I cut the release just as I always did (just a `lein deploy`).

**Comment by bbatsov** [comment]
It seems something's wrong with the CI and it hasn't been triggering for a few days - https://circleci.com/gh/clojure-emacs/orchard/tree/master

I get a bunch of local failures as well, and I assume they are related to #89 by @arichiardi, as it this was the only notable change recently.

**Comment by liquidz** [comment]
Oh, I was misunderstanding that you were using `make release`.

**Comment by bbatsov** [comment]
I had forgotten it even exists. I do use `make deploy`, but it's more or less the same as `make deploy clojars`.

Btw, are you getting lots of failing tests when doing `make test` locally?

**Comment by liquidz** [comment]
> Btw, are you getting lots of failing tests when doing make test locally?

No errors in orchard itself.
```
Ran 112 tests containing 506 assertions.
0 failures, 0 errors.
```

On the other hand, I'm getting failures in`iced-nrepl` test.
https://github.com/liquidz/iced-nrepl/runs/723767673?check_suite_focus=true

**Comment by bbatsov** [comment]
Weird. I keep getting 11 errors (mostly to do with Java class/members info) with and without #89.

**Comment by bbatsov** [comment]
Anyways, I can reproduce your problem but I still have no idea what causes it. I tried reverting #89, but I still get this error and there no other material commits in this release (or at least none of them seems related to me). I'll keep digging.

**Comment by arichiardi** [comment]
Oh strange, I will also try to see what's going on. It definitely seems unrelated as a first glance... Will also report back.

**Comment by liquidz** [comment]
In clojars, 0.5.9 depends on clojure 1.10.1 while other versions not.
- https://clojars.org/cider/orchard/versions/0.5.9
- https://clojars.org/cider/orchard/versions/0.5.8

Could it be relevant?

**Comment by bbatsov** [comment]
Yeah, this seems like something that could be relevant, but the dependencies of the project haven't been changed in 0.5.8. Clojure is supposed to be a provided dependency, not an explicit dependency. I'm wondering if that's not some bug in Lein 2.9.3, as I think I've recently upgraded to it.

**Comment by bbatsov** [comment]
I'm now pretty sure that @liquidz is right and the extra dep is breaking things, but I still can't think of anything that might be causing this other than might suggestion about a Lein bug. Any help/ideas would be welcome!

**Comment by bbatsov** [comment]
@clojure-emacs/cider Can someone with an older Lein try a make install and check the generated pom.xml in the jar?

**Comment by bbatsov** [comment]
I can confirm that downgrading to Lein 2.9.1 fixed this. I've issued 0.5.10 that works just fine, but I guess I'll also have to report this issue upstream. I have no idea which change in Lein caused it.

**Comment by liquidz** [comment]
Thanks!
I also confirmed iced-nrepl's test passes with 0.5.10.
https://github.com/liquidz/iced-nrepl/runs/736200238?check_suite_focus=true

**Comment by bbatsov** [comment]
I've reported the issue upstream to Leiningen. Hopefully someone will be able to track down the exact problem.

**Comment by bbatsov** [comment]
The Leiningen issue (https://github.com/technomancy/leiningen/issues/2687) was just fixed in https://github.com/technomancy/leiningen/commit/8fb39db7f3581e106320bc3170a77108f295d859 Long story short - composite profiles are incompatible with `provided` and now that's explicit.
